plugins {
    id 'java'
}

group = 'org.jamesyeap'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Aeron
    implementation 'io.aeron:aeron-all:1.51.0'

    // SLF4J facade with Log4j2 backend
    implementation 'org.slf4j:slf4j-api:2.0.13'
    implementation 'org.slf4j:log4j-over-slf4j:2.0.18'
    runtimeOnly 'org.apache.logging.log4j:log4j-api:2.23.1'
    runtimeOnly 'org.apache.logging.log4j:log4j-core:2.23.1'
    runtimeOnly 'org.apache.logging.log4j:log4j-slf4j2-impl:2.23.1'

    // SBE
    compileOnly "uk.co.real-logic:sbe-tool:${SBE_VERSION}"

    // Testing
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'io.aeron:aeron-agent:1.51.0'
}

test {
    useJUnitPlatform()
}

// output directory for generated SBE class files
var generatedSbeDir = layout.buildDirectory.dir("generated/sbe").get().asFile
tasks.register('generateMessages', JavaExec) {
    group = 'sbe'
    mainClass = 'uk.co.real_logic.sbe.SbeTool'
    classpath = sourceSets.main.compileClasspath
    systemProperties('sbe.output.dir': generatedSbeDir,
            'sbe.target.language': 'Java',
            'sbe.validation.stop.on.error': 'true',
            'sbe.validation.xsd': "${SBE_VALIDATION_XSD}")
    args = ["${SBE_DEFINITION}"]
}

sourceSets {
    main {
        java {
            srcDir generatedSbeDir
        }
    }
}
