#!/usr/bin/env bash

# === AUTOGENERATED ===
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

# === IMPORTS ===
source "${SCRIPT_DIR}/common.sh"

# === CONFIG ===
AERON_DIR="/tmp/media-driver-1"
AERON_ARCHIVE_DIR="/tmp/archive-media-driver-1"

# === START ===
exec ${JAVA_HOME}/bin/java \
    -cp "${REPO_ROOT}/build/libs/aeron-playground-1.0-SNAPSHOT.jar:${AERON_LIB_JAR}:${LOGGING_JARS}" \
    -DaeronPlayground.dir=${AERON_DIR} \
    -DaeronPlayground.archiveDir=${AERON_ARCHIVE_DIR} \
    -DaeronPlayground.controlRequestChannel="aeron:udp?endpoint=localhost:8010" \
    -DaeronPlayground.controlRequestStream="52" \
    -DaeronPlayground.replicationChannel="aeron:udp?endpoint=localhost:8011" \
    -javaagent:${AERON_AGENT_JAR} \
    -Daeron.event.log.filename="${REPO_ROOT}/logs/archiverDebug.log" \
    -Daeron.event.archive.log="all" \
    ${ADD_OPENS} \
    ${VM_OPTIONS} \
    StartArchiver

# -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5104 \

# == DOCS FOR TURNING ON DEBUG LOGGING FOR AERON ==
# aeron.event.log.filename: System property for the file to which the log is appended. If not set then STDOUT will be used. Logging to file is significantly more efficient than logging to STDOUT.
# aeron.event.log.file.max.length: The maximum length of the file if the aeron.event.log.filename value is set. When the log writes past this length, the a new file will be created and the existing one renamed (Since Aeron 1.52.0).
# aeron.event.buffer.length: System property for length of the in-memory buffer used between the capture pointcut and the log reader. Defaults to 8MB.
# aeron.event.log.reader.classname: System property for the log reader class which consumes the event buffer. Defaults to io.aeron.agent.EventLogReaderAgent.
# aeron.event.log: System property containing a comma separated list of Driver event codes. These are also special events: all for all possible events and admin for administration events.
# aeron.event.log.disable: System property containing a comma separated list of Driver events to exclude.
# aeron.event.archive.log: System property containing a comma separated list of Archive event codes. all can be used to enable all Archive events.
# aeron.event.archive.log.disable: System property containing a comma separated list of Archive events to exclude.
# aeron.event.cluster.log: System property containing a comma separated list of Cluster event codes. all can be used to enable all Cluster events.
# aeron.event.cluster.log.disable: System property containing a comma separated list of Cluster events to exclude.

# -Daeron.event.log.filename=
# -Daeron.event.log.file.max.length=
# -Daeron.event.buffer.length=
# -Daeron.event.log.reader.classname=
# -Daeron.event.log=
# -Daeron.event.log.disable=
# -Daeron.event.archive.log=
# -Daeron.event.archive.log.disable=
# -Daeron.event.cluster.log=
# -Daeron.event.cluster.log.disable=