#!/usr/bin/env bash

# === AUTOGENERATED ===
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

# === IMPORTS ===
source "${SCRIPT_DIR}/common.sh"

# === CONFIG ===
AERON_DIR="/tmp/media-driver-1"
AERON_DEBUG_LOG_FILE="${REPO_ROOT}/logs/mediaDriverDebug.log"

# === DEBUG LOGGING FOR AERON ===
AERON_DEBUG_LOGGING_PROPS=(
  -javaagent:${AERON_AGENT_JAR}
  -Daeron.event.log.filename=${AERON_DEBUG_LOG_FILE}
  -Daeron.event.log="all"
)

# === START ===
exec ${JAVA_HOME}/bin/java \
    -cp "${REPO_ROOT}/apps/media-driver/build/libs/media-driver-1.0-SNAPSHOT-all.jar" \
    -DaeronPlayground.dir=${AERON_DIR} \
    ${ADD_OPENS} \
    ${VM_OPTIONS} \
    "${AERON_DEBUG_LOGGING_PROPS[@]}" \
    StartMediaDriver

# -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5104 \
