# === AUTOGENERATED ===
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# === SIGNAL HANDLER ===
cleanup() {
  echo ""
  echo "Shutting down all processes..."

  # Kill all background processes
  while IFS= read -r pid; do
    if kill -0 "$pid" 2>/dev/null; then
      echo "Killing process $pid..."
      kill "$pid" 2>/dev/null
    fi
  done < "$SCRIPT_DIR/tmp/c.pid"

  # Clear the PID file
  echo "" > "$SCRIPT_DIR/tmp/c.pid"

  echo "Cleanup complete. Exiting."
  exit 0
}

# Trap Ctrl+C (SIGINT) and call cleanup
trap cleanup SIGINT

# === START ===
$SCRIPT_DIR/startMediaDriver.sh &
echo "$!" >> $SCRIPT_DIR/tmp/c.pid

$SCRIPT_DIR/startArchiver.sh &
echo "$!" >> $SCRIPT_DIR/tmp/c.pid

$SCRIPT_DIR/startPublisher.sh &
echo "$!" >> $SCRIPT_DIR/tmp/c.pid

$SCRIPT_DIR/startSubscriber.sh &
echo "$!" >> $SCRIPT_DIR/tmp/c.pid

# Wait forever (until Ctrl+C is pressed)
wait

