# === AUTOGENERATED ===
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

# === SIGNAL HANDLER ===
cleanup() {
  echo ""
  echo "Shutting down all processes..."

  # Kill all background processes
  while IFS= read -r pid; do
    if kill -0 "$pid" 2>/dev/null; then
      echo "Killing process $pid..."
      kill "$pid" 2>/dev/null
    fi
  done < "$SCRIPT_DIR/tmp/c.pid"

  # Remove the PID file
  rm -f "$SCRIPT_DIR/tmp/c.pid"

  # Remove the aeron media driver and aeron archive directories
  rm -rf /tmp/media-driver-1
  rm -rf /tmp/archive-media-driver-1

  echo "Cleanup complete. Exiting."
  exit 0
}

# Trap Ctrl+C (SIGINT) and call cleanup
trap cleanup SIGINT

# === START ===
${REPO_ROOT}/gradlew build

$SCRIPT_DIR/startMediaDriver.sh &
echo "$!" >> $SCRIPT_DIR/tmp/c.pid

$SCRIPT_DIR/startArchiver.sh &
echo "$!" >> $SCRIPT_DIR/tmp/c.pid

$SCRIPT_DIR/startPublisher.sh &
echo "$!" >> $SCRIPT_DIR/tmp/c.pid

$SCRIPT_DIR/startSubscriber.sh &
echo "$!" >> $SCRIPT_DIR/tmp/c.pid

# Wait forever (until Ctrl+C is pressed)
wait

