#!/usr/bin/env bash

# === CONFIG ===
AERON_DIR="/tmp/media-driver-1"
AERON_CHANNEL="aeron:udp?endpoint=127.0.0.1:12345"
AERON_STREAM="51"

# === AUTOGENERATED ===
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

# === START ===
source "${SCRIPT_DIR}/common.sh"

${JAVA_HOME}/bin/java \
    -cp "${REPO_ROOT}/build/libs/aeron-playground-1.0-SNAPSHOT.jar:${AERON_LIB_JAR}" \
    -XX:+UnlockExperimentalVMOptions \
    -XX:+TrustFinalNonStaticFields \
    -XX:+UnlockDiagnosticVMOptions \
    -XX:GuaranteedSafepointInterval=300000 \
    -XX:+UseParallelGC \
    -DaeronPlayground.dir=${AERON_DIR} \
    -DaeronPlayground.channel=${AERON_CHANNEL} \
    -DaeronPlayground.stream=${AERON_STREAM} \
    ${ADD_OPENS} \
    Subscriber

# -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5104 \
