#!/usr/bin/env bash

# === CONFIG ===
AERON_DIR="/tmp/media-driver-1"
AERON_ARCHIVE_DIR="/tmp/archive-media-driver-1"

# === AUTOGENERATED ===
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

# === START ===
source "${SCRIPT_DIR}/common.sh"

exec ${JAVA_HOME}/bin/java \
    -cp "${REPO_ROOT}/build/libs/aeron-playground-1.0-SNAPSHOT.jar:${AERON_LIB_JAR}:${LOGGING_JARS}" \
    -DaeronPlayground.dir=${AERON_DIR} \
    -DaeronPlayground.archiveDir=${AERON_ARCHIVE_DIR} \
    -DaeronPlayground.controlRequestChannel="aeron:udp?endpoint=localhost:8010" \
    -DaeronPlayground.controlRequestStream="52" \
    -DaeronPlayground.replicationChannel="aeron:udp?endpoint=localhost:8011" \
    ${ADD_OPENS} \
    ${VM_OPTIONS} \
    StartArchiver

# -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5104 \
