#!/usr/bin/env bash

# === CONFIG ===
AERON_DIR="/tmp/media-driver-1"
AERON_CHANNEL="aeron:udp?endpoint=127.0.0.1:12345"
AERON_STREAM="51"

# === AUTOGENERATED ===
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

# === START ===
source "${SCRIPT_DIR}/common.sh"

exec ${JAVA_HOME}/bin/java \
    -cp "${REPO_ROOT}/build/libs/aeron-playground-1.0-SNAPSHOT.jar:${AERON_LIB_JAR}:${LOGGING_JARS}" \
    -DaeronPlayground.dir=${AERON_DIR} \
    -DaeronPlayground.channel=${AERON_CHANNEL} \
    -DaeronPlayground.stream=${AERON_STREAM} \
    -DaeronPlayground.controlRequestChannel="aeron:udp?endpoint=localhost:8010" \
    -DaeronPlayground.controlRequestStream="52" \
    -DaeronPlayground.controlResponseChannel="aeron:udp?endpoint=localhost:0" \
    -DaeronPlayground.controlResponseStream="53" \
    ${ADD_OPENS} \
    ${VM_OPTIONS} \
    Publisher

# -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5104 \
