#!/usr/bin/env bash

# === AUTOGENERATED ===
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

# === CONFIG ===
AERON_DIR="/tmp/media-driver-1"
AERON_CHANNEL="aeron:udp?endpoint=127.0.0.1:12345"
AERON_STREAM="51"
REPLAY_STREAM="61"
REPLAY_CONTROL_REQUEST_CHANNEL="aeron:udp?endpoint=localhost:8010"
REPLAY_CONTROL_REQUEST_STREAM="52"
REPLAY_CONTROL_RESPONSE_CHANNEL="aeron:udp?endpoint=localhost:0"
REPLAY_CONTROL_RESPONSE_STREAM="53"

# === IMPORTS ===
source "${SCRIPT_DIR}/common.sh"

# === START ===
exec ${JAVA_HOME}/bin/java \
    -cp "${REPO_ROOT}/apps/subscriber/build/libs/subscriber-1.0-SNAPSHOT-all.jar" \
    -DaeronPlayground.dir=${AERON_DIR} \
    -DaeronPlayground.channel=${AERON_CHANNEL} \
    -DaeronPlayground.stream=${AERON_STREAM} \
    -DaeronPlayground.shouldReplay="true" \
    -DaeronPlayground.replayStream=${REPLAY_STREAM} \
    -DaeronPlayground.controlRequestChannel=${REPLAY_CONTROL_REQUEST_CHANNEL} \
    -DaeronPlayground.controlRequestStream=${REPLAY_CONTROL_REQUEST_STREAM} \
    -DaeronPlayground.controlResponseChannel=${REPLAY_CONTROL_RESPONSE_CHANNEL} \
    -DaeronPlayground.controlResponseStream=${REPLAY_CONTROL_RESPONSE_STREAM} \
    ${ADD_OPENS} \
    ${VM_OPTIONS} \
    subscriber.Subscriber

# -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5104 \
